// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace BazyDanych.Data.BazyDanych
{
    public partial class AspnetBazydanychFE03AB7A0D1F48FA9C62B214EBB023F7Context : DbContext
    {
        public AspnetBazydanychFE03AB7A0D1F48FA9C62B214EBB023F7Context()
        {
        }

        public AspnetBazydanychFE03AB7A0D1F48FA9C62B214EBB023F7Context(DbContextOptions<AspnetBazydanychFE03AB7A0D1F48FA9C62B214EBB023F7Context> options)
            : base(options)
        {
        }

        public virtual DbSet<WeatherForecast> WeatherForecast { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<WeatherForecast>(entity =>
            {
                entity.Property(e => e.Date).HasColumnType("datetime");

                entity.Property(e => e.Summary).HasMaxLength(50);

                entity.Property(e => e.UserName).HasMaxLength(50);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}